/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package badcode;

import java.util.HashSet;
import java.util.Set;

/**
 *
 * @author zamiljitu
 */
public class CourseOutlineForm extends javax.swing.JFrame {

    /**
     * Creates new form CostsOfDrivingAVehicle
     */
    public CourseOutlineForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnGrp = new javax.swing.ButtonGroup();
        jlblCNo = new javax.swing.JLabel();
        jTxtCNo = new javax.swing.JTextField();
        jlblCName = new javax.swing.JLabel();
        jTxtCName = new javax.swing.JTextField();
        jlblCType = new javax.swing.JLabel();
        jCmBCType = new javax.swing.JComboBox<>();
        jBtnGen = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtCoutline = new javax.swing.JTextArea();
        jrdoFCourse = new javax.swing.JRadioButton();
        jrdoHCourse = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Course Outline Form");
        setResizable(false);

        jlblCNo.setText("Course no: ");

        jlblCName.setText("Course name: ");

        jlblCType.setText("Course type: ");

        jCmBCType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inclass", "Online" }));

        jBtnGen.setText("Generate Course Outline");
        jBtnGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGenActionPerformed(evt);
            }
        });

        jtxtCoutline.setColumns(20);
        jtxtCoutline.setRows(5);
        jScrollPane1.setViewportView(jtxtCoutline);

        jBtnGrp.add(jrdoFCourse);
        jrdoFCourse.setSelected(true);
        jrdoFCourse.setText("Full course");

        jBtnGrp.add(jrdoHCourse);
        jrdoHCourse.setText("Half course");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 280, Short.MAX_VALUE)
                        .addComponent(jBtnGen))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlblCType)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCmBCType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlblCName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtCName))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlblCNo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtCNo))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jrdoFCourse)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jrdoHCourse)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblCNo)
                    .addComponent(jTxtCNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblCName)
                    .addComponent(jTxtCName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCmBCType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblCType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrdoHCourse)
                    .addComponent(jrdoFCourse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnGen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGenActionPerformed
        // TODO add your handling code here:
        
        CourseDetails cd = new CourseDetails();
        cd.setCourseNumber(jTxtCNo.getText());
        cd.setCourseTitle(jTxtCName.getText());
        cd.setCourseType(jCmBCType.getSelectedItem().toString());
        if (jrdoFCourse.isSelected()){
            cd.setCourseSize("Full");
        }
        else{
            cd.setCourseSize("Half");
        }

        jtxtCoutline.setText(cd.printHeader());
        jtxtCoutline.append(cd.generateCourseOutline());
    }//GEN-LAST:event_jBtnGenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CourseOutlineForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CourseOutlineForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CourseOutlineForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CourseOutlineForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CourseOutlineForm().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnGen;
    private javax.swing.ButtonGroup jBtnGrp;
    private javax.swing.JComboBox<String> jCmBCType;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxtCName;
    private javax.swing.JTextField jTxtCNo;
    private javax.swing.JLabel jlblCName;
    private javax.swing.JLabel jlblCNo;
    private javax.swing.JLabel jlblCType;
    private javax.swing.JRadioButton jrdoFCourse;
    private javax.swing.JRadioButton jrdoHCourse;
    private javax.swing.JTextArea jtxtCoutline;
    // End of variables declaration//GEN-END:variables
}