delete from seat_reservation;
delete from fares;
delete from leg_instance;
delete from flight_leg;
delete from flight;
delete from airport;
commit;
drop table seat_reservation;
drop table fares;
drop table leg_instance;
drop table flight_leg;
drop table flight;
drop table airport;
commit;
